[theme]
primaryColor = "#2dba73"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#161b22"
textColor = "#ffffff"
font = "sans serif"

[server]
maxUploadSize = 500
statusBoxVisible = false

[browser]
toolbarTimeout = "seconds"
gatherUsageStats = false

[client]
showErrorDetails = false